name: "Jest badges generation action"
description: "Action generating jest coverage badges and pushing them to the repo"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: check-square
  color: green
