name: checks
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: './'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Setting yarn version
        run: yarn policies set-version 1.22.10

      - name: Install dependencies
        run: yarn install

      - name: Tests
        run: yarn test:ci

      - name: Generate badges
        uses: ./
