name: Coverage badges generation & version bump
on:
  release:
    types: [published]
jobs:
  update-latest:
    name: Rebase latest on master
    runs-on: ubuntu-latest
    needs: [bump-package]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout latest
        run: git checkout latest
      - name: Rebase latest on master
        run: git merge master
      - name: Push latest
        run: git push origin latest
