name: Updating latest branch
on:
  release:
    types: [published]
jobs:
  update-latest:
    name: Rebase latest on master
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout latest
        run: git checkout latest

      - name: Rebase latest on master
        run: git merge origin/master

      - name: Push latest
        run: git push origin latest
